### ISSUE TITLE
no attribute AVAILABLE, no attribute uuid

### ISSUE THREAD

**Issue by ghost** [ilgarm/terminator_plugins#2] opened 2016-02-21 23:56 UTC
I'm not a python person but I'm going to look into fixing this issue.  I just thought I would share the info.

The menu items do show up but they don't perform the function.  If the terminator is lauched from another emulator then we get some output.  The first comes on terminators initialization.

```
PluginRegistry::load_plugins: Importing plugin __init__.py failed: 'module' object has no attribute 'AVAILABLE'
```

No trace is given.

Signing into ssh gives no issue.

Cloning vertically or horizontally gives this traceback.

```
Traceback (most recent call last):
  File "/home/k/.config/terminator/plugins/clone_session.py", line 69, in clone_session
    sibling.spawn_child_with_command(cmd)
  File "/home/k/.config/terminator/plugins/clone_session.py", line 198, in spawn_child_with_command
    envv.append('TERMINATOR_UUID=%s' % self.uuid.urn)
AttributeError: 'ClonableTerminal' object has no attribute 'uuid'
```

~~I've noticed that this has worked for others without flaw so I suspect this might be a python2/3 issue.  This is on arch where python3 is the default python.~~  Edit: It would not get that far with python3.

**Comment by ghost** [comment] 2016-02-22 00:19
Confirmed.  This is a bug related to Arch main repository installation.  AUR does not have the bug.

Not sure if this should be considered a bug here or there.  No other plugin fails and this plugin doesn't work against a package in a major distro.  I could see it either way.

**Comment by ilgarm** [comment] 2017-03-28 11:27
duplicate of #3

**Closed as completed by ilgarm** 2017-03-28 11:27 UTC
